# Add Margin Demo

In [1]:
from datasets import (Dataset, MFCCData, RAVDESSUnifiedLabel)
from tools import add_margin, IndexPicker

from config import DATASET_PATH

In [2]:
import numpy as np

## Test Samples

In [3]:
test_samples = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
test_samples

array([[1, 2],
       [3, 4],
       [5, 6]])

### Add Margin

In [5]:
index_picker = IndexPicker(2, 2)
%time test_margined = np.array(add_margin(test_samples, index_picker))

CPU times: user 244 µs, sys: 94 µs, total: 338 µs
Wall time: 311 µs


In [6]:
test_margined

array([[[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [1, 2],
        [3, 4],
        [5, 6],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]]])

In [7]:
test_margined.shape

(3, 5, 2)

### Reshape

In [8]:
n_samples,window_length,n_features = test_margined.shape

In [9]:
test_reshaped = np.array(np.reshape(test_margined, (n_samples, -1)))

In [10]:
test_reshaped.shape

(3, 10)

In [11]:
test_reshaped

array([[1, 2, 1, 2, 1, 2, 3, 4, 5, 6],
       [1, 2, 1, 2, 3, 4, 5, 6, 5, 6],
       [1, 2, 3, 4, 5, 6, 5, 6, 5, 6]])

In [12]:
(test_reshaped[-1] == test_margined[-1].flatten()).all()

True

In [13]:
test_reshaped_ = np.array(np.reshape(test_margined, (-1, n_features)))

In [14]:
test_reshaped_.shape

(15, 2)

In [15]:
test_reshaped_

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [5, 6]])

In [16]:
(test_reshaped_[0:window_length].flatten() == test_margined[0].flatten()).all()

True

## Ravdess Samples

In [17]:
ravdess_path = DATASET_PATH.format(language="english", name="RAVDESS", form="mfcc")

%time ravdess = Dataset(ravdess_path, MFCCData(), RAVDESSUnifiedLabel())

CPU times: user 7.94 s, sys: 329 ms, total: 8.27 s
Wall time: 8.27 s


In [18]:
samples = ravdess.samples

In [19]:
X = np.array(list(samples['coefficients']))

In [20]:
y = np.array(list(samples['emotion']))

### Add Margin

In [21]:
index_picker = IndexPicker(10, 10)
%time X_margined = np.array(add_margin(X, index_picker))

CPU times: user 4.51 s, sys: 1.65 s, total: 6.16 s
Wall time: 6.21 s


In [22]:
X_margined.shape

(529974, 21, 39)

### Reshape

In [23]:
n_samples,window_length,n_features = X_margined.shape
X_reshaped = np.array(np.reshape(X_margined, (n_samples, -1)))

In [24]:
X_reshaped.shape

(529974, 819)

In [25]:
(X_reshaped[-1] == X_margined[-1].flatten()).all()

True

In [26]:
X_reshaped_ = np.array(np.reshape(X_margined, (-1, n_features)))

In [27]:
X_reshaped_.shape

(11129454, 39)

In [28]:
(X_reshaped_[0:window_length].flatten() == X_margined[0].flatten()).all()

True

In [29]:
X_reshaped_[:window_length].flatten()

array([-1.65572128e+01, -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,
        1.47547948e+00,  2.03847051e+00,  1.24704850e+00,  9.19048131e-01,
       -6.19274712e+00, -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,
        1.29758329e+01, -5.27952790e-01,  3.89949292e-01, -3.25553422e-03,
       -1.09376289e-01,  8.45553994e-01,  7.08550751e-01, -1.58509123e+00,
       -7.03012198e-02,  2.30384302e+00, -1.06417201e-01, -2.09265423e+00,
       -1.92504495e-01,  8.53481948e-01,  3.38864028e-01,  2.02220246e-01,
        2.11202577e-01, -2.09314659e-01, -3.51897150e-01, -4.72320467e-01,
        1.95141777e-01, -9.61367339e-02, -8.96789059e-02,  2.89654911e-01,
        3.76539409e-01, -5.81700020e-02, -6.49766862e-01, -1.65572128e+01,
       -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,  1.47547948e+00,
        2.03847051e+00,  1.24704850e+00,  9.19048131e-01, -6.19274712e+00,
       -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,  1.29758329e+01,
       -5.27952790e-01,  

In [30]:
X_margined[0].flatten()

array([-1.65572128e+01, -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,
        1.47547948e+00,  2.03847051e+00,  1.24704850e+00,  9.19048131e-01,
       -6.19274712e+00, -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,
        1.29758329e+01, -5.27952790e-01,  3.89949292e-01, -3.25553422e-03,
       -1.09376289e-01,  8.45553994e-01,  7.08550751e-01, -1.58509123e+00,
       -7.03012198e-02,  2.30384302e+00, -1.06417201e-01, -2.09265423e+00,
       -1.92504495e-01,  8.53481948e-01,  3.38864028e-01,  2.02220246e-01,
        2.11202577e-01, -2.09314659e-01, -3.51897150e-01, -4.72320467e-01,
        1.95141777e-01, -9.61367339e-02, -8.96789059e-02,  2.89654911e-01,
        3.76539409e-01, -5.81700020e-02, -6.49766862e-01, -1.65572128e+01,
       -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,  1.47547948e+00,
        2.03847051e+00,  1.24704850e+00,  9.19048131e-01, -6.19274712e+00,
       -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,  1.29758329e+01,
       -5.27952790e-01,  

In [31]:
X_reshaped[0]

array([-1.65572128e+01, -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,
        1.47547948e+00,  2.03847051e+00,  1.24704850e+00,  9.19048131e-01,
       -6.19274712e+00, -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,
        1.29758329e+01, -5.27952790e-01,  3.89949292e-01, -3.25553422e-03,
       -1.09376289e-01,  8.45553994e-01,  7.08550751e-01, -1.58509123e+00,
       -7.03012198e-02,  2.30384302e+00, -1.06417201e-01, -2.09265423e+00,
       -1.92504495e-01,  8.53481948e-01,  3.38864028e-01,  2.02220246e-01,
        2.11202577e-01, -2.09314659e-01, -3.51897150e-01, -4.72320467e-01,
        1.95141777e-01, -9.61367339e-02, -8.96789059e-02,  2.89654911e-01,
        3.76539409e-01, -5.81700020e-02, -6.49766862e-01, -1.65572128e+01,
       -2.37675238e+00, -2.43022060e+00,  5.32652903e+00,  1.47547948e+00,
        2.03847051e+00,  1.24704850e+00,  9.19048131e-01, -6.19274712e+00,
       -2.39648557e+00,  2.39563942e+00,  3.64896917e+00,  1.29758329e+01,
       -5.27952790e-01,  