In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [2]:
data = np.array([[1, 2], 
                 [3, 4],
                 [5, 6]])

### Original

In [3]:
scaler = MinMaxScaler()

In [4]:
scaler.fit_transform(data)

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

### Desired

In [5]:
data_reshaped = data.reshape(-1, 1)
print(data_reshaped)

data_scaled = scaler.fit_transform(data_reshaped)
data_scaled.reshape(1,-1,2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


array([[[-1.46385011, -0.87831007],
        [-0.29277002,  0.29277002],
        [ 0.87831007,  1.46385011]]])

### Into Function

In [6]:
def scale(X, scaler):
    original_shape = X.shape
    X_reshaped = X.reshape(-1, 1)
    X_scaled = scaler.fit_transform(X_reshaped)
    return X_scaled.reshape(original_shape)

In [7]:
scale(data, scaler)

array([[-1.46385011, -0.87831007],
       [-0.29277002,  0.29277002],
       [ 0.87831007,  1.46385011]])

### Into Class

In [8]:
from sklearn.base import TransformerMixin,BaseEstimator


class Scaler(BaseEstimator,TransformerMixin):

    def __init__(self, scaler):
        self.scaler = scaler

    def fit(self,X,y=None):
        self.scaler.fit(X.reshape(-1, 1))
        return self

    def transform(self,X):
        return self.scaler.transform(X.reshape(-1, 1)).reshape(X.shape)

In [9]:
scaler = Scaler(scaler)
scaler.fit_transform(data)

array([[-1.46385011, -0.87831007],
       [-0.29277002,  0.29277002],
       [ 0.87831007,  1.46385011]])